on:
  push:
    branches: [main]
    tags:
      - 'v*'   # e.g., v1.0.0, v2.1.3

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract tag (if present)
        id: vars
        run: |
          TAG=${GITHUB_REF##*/}
          echo "DOCKER_TAG=$TAG" >> $GITHUB_OUTPUT
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build and push Docker image (main branch)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shfmt:latest

      - name: Build and push Docker image (tagged release)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shfmt:${{ steps.vars.outputs.DOCKER_TAG }}t 